### ISSUE TITLE
Wrong links to the github in many of the wikis

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/lapis-wiki#9]
Wrong links to the github in many of the wikis in the right top corner

examples:
https://www2.foundation.grid.tf/#/
https://info.grid.tf/#/concepts/cloud_units
https://info.grid.tf/#/concepts/cloud_units
etc

Solution 1: Give ability to edit link in wiki settings file.
Solution 2: Change links in the code

**Comment by nbabenko** [comment]
its not blocker, but certainly not good for production

**Comment by nbabenko** [comment]
Wikis with the wrong github links:
https://wiki.tokens.grid.tf/#/
https://wiki.grid.tf/#/

**Comment by ranatrk** [comment]
The following approaches were investigated and discussed today with @abom : 
1. Remove the hard coded 'token_' added to the link in `docsify_config.js` line 11 resulting in the redirection to be 
https://github.com/threefoldfoundation/info_info_tokens instead of https://github.com/threefoldfoundation/info_tokens
issue: This is a fix for only this specific issue, but will fail with any other repo url used that doesn't belong to threefolfoundation

2. Change the folder name in the loaded docsites to be the name of the repository instead of the name given when publishing.
issue: The repositories are cloned (2 branches) in /sandbox/code/github/**_foundation_**/**_repo_name_** , and then loaded to /sandbox/var/docsites/_**name**_ where the name is the given name. Therefore if that name was to be repo_name, Each repository can only be published once. Where in the current case the repository can be loaded multiple times under different names

3. **TO BE INVESTIGATED:** Creating a hidden file when writing in the docsites, where this hidden file will contain information about the repository. This information can then be obtained by reading the file. The repo url will be there and used rather than hard coding it for the redirection

**Comment by ranatrk** [comment]
Update: **option 3** is still being investigated, the hidden file is saved but still trying to read/use its content to replace the link used for the redirection

**Comment by ranatrk** [comment]
The following snippets of code were added to try and display a different (hard coded for now) link but the repo link  at the final step was empty and not "_https://github.com/threefoldfoundation/info_tokens_" therefore still investigating.

**in ../OpenPublish/applications/wiki.moon:**
```        
if file == ".repo"
            @repo = "https://github.com/threefoldfoundation/info_tokens"
```

**in ../OpenPublish/views/wiki/index.etlua:**
```
docsifyConfig("<%- name %>","<%- repo %>" <%- all_pages %>);

```

**in ../OpenPublish/static/wiki/js/docsify_config.js:**
```
repo: repo,
```

**Comment by ranatrk** [comment]
still testing and adjusting option 3

**Comment by ranatrk** [comment]
**Option 3** is working fine, but investigating another option that doesn't require saving and reading from new files:
**option 4**: Add the repo url to the generated virtual hosts file of nginx and use that instead. Still trying to add the repo_rul to the generated conf file

**Comment by ranatrk** [comment]
**Option 4** will only work when using the domain name but not the IP therefore was disregarded for now.

Fixes done using **option 3** in OpenPublish and JumpscaleX.

>     3. Creating a hidden file when writing in the docsites, where this hidden file will contain information about the repository. This information can then be obtained by reading the file. The repo url will be there and used rather than hard coding it for the redirection
